/*
 * Generated by Robotoworks Mechanoid
 */
package eu.masconsult.template.recipes.ops;

import eu.masconsult.template.recipes.ops.AbstractRecipesService;

public class RecipesService extends AbstractRecipesService {
	public RecipesService() {
		super(false);
	}
}
