/*
 * Generated by Robotoworks Mechanoid
 */
package eu.masconsult.template.recipes.ops;

public class RecipesServiceOperationConfigurationRegistry extends AbstractRecipesServiceOperationConfigurationRegistry {
	
}

