/*
 * Generated by Robotoworks Mechanoid
 */
package eu.masconsult.template.recipes.ops;

import com.robotoworks.mechanoid.ops.OperationService;

public class RecipesServiceProcessor extends AbstractRecipesServiceProcessor {
	public RecipesServiceProcessor(OperationService service) {
		super(service, false);
	}
}
