/*
 * Generated by Robotoworks Mechanoid
 */
package eu.masconsult.template.recipes.content.migrations;

import android.database.sqlite.SQLiteDatabase;
import com.robotoworks.mechanoid.db.SQLiteMigration;

public class DefaultRecipesDBMigrationV2 extends SQLiteMigration {
	@Override
	public void onBeforeUp(SQLiteDatabase db) {}
	
	@Override
	public void up(SQLiteDatabase db) {
		db.execSQL(
			"alter table recipes add column recipe_id text "
		);	
		db.execSQL(
			"create index idx_recipe_id on recipes ( recipe_id ) "
		);	
	}
	
	@Override
	public void onAfterUp(SQLiteDatabase db) {}
}
