/*
 * Generated by Robotoworks Mechanoid
 */
package eu.masconsult.template.recipes.content;

import android.content.Context;
import eu.masconsult.template.recipes.content.AbstractRecipesDBOpenHelper;

public class RecipesDBOpenHelper extends AbstractRecipesDBOpenHelper {
	public RecipesDBOpenHelper(Context context) {
		super(context);
	}
}
