/*
 * Generated by Robotoworks Mechanoid
 */
package eu.masconsult.template.recipes.ops;

import com.robotoworks.mechanoid.ops.OperationProcessor;
import com.robotoworks.mechanoid.ops.OperationService;
import com.robotoworks.mechanoid.ops.OperationServiceConfiguration;

import eu.masconsult.template.recipes.ops.RecipesServiceProcessor;

public abstract class AbstractRecipesService extends OperationService {
	
	public static final OperationServiceConfiguration CONFIG = new RecipesServiceConfiguration();
	
	@Override
	protected OperationProcessor createProcessor() {
		return new RecipesServiceProcessor(this);
	}
	
	public AbstractRecipesService(boolean enableLogging) {
		super(enableLogging);
	}
}
